// Package webhook tests for the GitHub webhook handler and helpers.
package webhook

import (
	"strings"
	"testing"
	"time"
)

// TestVerifySignature checks the HMAC-SHA256 verification with a known
// payload/secret/signature triple. The known vector was generated by the
// GitHub webhook test suite.
func TestVerifySignature(t *testing.T) {
	secret := "It's a Secret to Everybody"
	payload := []byte("Hello, World!")
	// Known GitHub signature for the above payload/secret.
	expected := "sha256=757107ea0eb2509fc211221cce984b8a37570b6d7586c22c46f4379c8b043e17"

	if !verifySignature(secret, payload, expected) {
		t.Fatal("verifySignature returned false for known valid signature")
	}
}

func TestVerifySignature_Invalid(t *testing.T) {
	tests := []struct {
		name   string
		secret string
		header string
		body   []byte
		want   bool
	}{
		{"empty secret", "", "sha256=abc", []byte("body"), false},
		{"empty header", "secret", "", []byte("body"), false},
		{"wrong prefix", "secret", "md5=abc", []byte("body"), false},
		{"tampered body", "secret", "sha256=" + strings.Repeat("a", 64), []byte("body"), false},
		{"wrong secret", "secret", "sha256=" + strings.Repeat("b", 64), []byte("body"), false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := verifySignature(tc.secret, tc.body, tc.header); got != tc.want {
				t.Errorf("verifySignature = %v, want %v", got, tc.want)
			}
		})
	}
}

// TestRecentDeliveries_SeenAndDeduplicate checks that the same delivery ID
// is only counted once within the TTL.
func TestRecentDeliveries_SeenAndDeduplicate(t *testing.T) {
	r := NewRecentDeliveries(time.Hour, 100)

	if r.Seen("delivery-1") {
		t.Fatal("first Seen should return false")
	}
	if !r.Seen("delivery-1") {
		t.Fatal("second Seen for same ID should return true")
	}
	if r.Seen("delivery-2") {
		t.Fatal("first Seen for new ID should return false")
	}
	if r.Size() != 2 {
		t.Errorf("expected 2 entries, got %d", r.Size())
	}
}

func TestRecentDeliveries_EmptyID(t *testing.T) {
	r := NewRecentDeliveries(time.Hour, 100)
	if r.Seen("") {
		t.Fatal("empty ID should never be seen")
	}
}

func TestRecentDeliveries_Expiry(t *testing.T) {
	r := NewRecentDeliveries(50*time.Millisecond, 100)
	r.Seen("delivery-1")
	// After the TTL expires, the same ID should be treated as new.
	time.Sleep(80 * time.Millisecond)
	if r.Seen("delivery-1") {
		t.Fatal("expired delivery should be treated as new")
	}
}

// TestMatchesCodePath checks the file-pattern filter that decides whether
// a PR is eligible for review.
func TestMatchesCodePath(t *testing.T) {
	tests := []struct {
		path string
		want bool
	}{
		{"server/internal/foo.go", true},
		{"builder/frontend/src/main.ts", false},
		{"runner/internal/controller/runner.go", true},
		{"server/proto/user/v1/user.proto", true},
		{"server/db/migrations/0001_init.sql", true},
		{"runner/db/migrations/abc.sql", true},
		{"docs/README.md", false},
		{"tools/skills/x/SKILL.md", false},
		{"README.md", false},
		{"foo.txt", false},
		{"some/path/file.go.bak", false}, // .bak ending is a different suffix
	}
	for _, tc := range tests {
		t.Run(tc.path, func(t *testing.T) {
			if got := matchesCodePath(tc.path); got != tc.want {
				t.Errorf("matchesCodePath(%q) = %v, want %v", tc.path, got, tc.want)
			}
		})
	}
}

// TestBuildReviewTaskRequest checks that the review task request is populated
// correctly from a ReviewContext.
func TestBuildReviewTaskRequest(t *testing.T) {
	review := ReviewContext{
		Trigger:       "file-pattern",
		Repo:          "chetter/chetter",
		PRNumber:      42,
		BaseRef:       "main",
		HeadRef:       "feat/some-thing",
		HeadCloneURL:  "https://github.com/someone/myapp.git",
		CommentAuthor: "",
		GitHubToken:   "ghs_test_token",
	}
	req := buildReviewTaskRequest(review)

	if req.Prompt == "" {
		t.Fatal("Prompt should be non-empty")
	}
	if req.GitURL != review.HeadCloneURL {
		t.Errorf("GitURL = %q, want %q", req.GitURL, review.HeadCloneURL)
	}
	if req.GitRef != review.HeadRef {
		t.Errorf("GitRef = %q, want %q", req.GitRef, review.HeadRef)
	}
	if req.Agent != "pr-reviewer" {
		t.Errorf("Agent = %q, want pr-reviewer", req.Agent)
	}
	if req.ProviderID != "opencode-go" {
		t.Errorf("ProviderID = %q, want opencode-go", req.ProviderID)
	}
	if req.ModelID != "minimax-m3" {
		t.Errorf("ModelID = %q, want minimax-m3", req.ModelID)
	}
	if req.TimeoutSec != 3600 {
		t.Errorf("TimeoutSec = %d, want 3600", req.TimeoutSec)
	}
	if req.AgentImage == "" {
		t.Error("AgentImage should be set so service.SubmitTask does not reject the request")
	}
	if got := req.Env["PR_NUMBER"]; got != "42" {
		t.Errorf("Env[PR_NUMBER] = %q, want 42", got)
	}
	if got := req.Env["GITHUB_TOKEN"]; got != "ghs_test_token" {
		t.Errorf("Env[GITHUB_TOKEN] = %q, want ghs_test_token", got)
	}
	if got := req.Env["GITHUB_REPO"]; got != "chetter/chetter" {
		t.Errorf("Env[GITHUB_REPO] = %q, want my-org/my-repo", got)
	}
	if _, ok := req.Env["COMMENT_AUTHOR"]; ok {
		t.Error("COMMENT_AUTHOR should not be set when CommentAuthor is empty")
	}
}

func TestBuildReviewTaskRequest_WithComment(t *testing.T) {
	review := ReviewContext{
		Trigger:       "comment",
		CommentAuthor: "someuser",
		Repo:          "chetter/chetter",
		PRNumber:      7,
		BaseRef:       "main",
		HeadRef:       "fix/x",
		HeadCloneURL:  "https://github.com/x.git",
		GitHubToken:   "t",
	}
	req := buildReviewTaskRequest(review)
	if got := req.Env["COMMENT_AUTHOR"]; got != "someuser" {
		t.Errorf("Env[COMMENT_AUTHOR] = %q, want someuser", got)
	}
}

// TestShouldReview_FilterLogic checks the filter that determines whether a
// PR should be reviewed, using a mocked GitHub client.
func TestShouldReview_FilterLogic(t *testing.T) {
	cases := []struct {
		name        string
		pr          PullRequest
		repo        string
		files       []string // files listed from API
		filesErr    error
		wantOK      bool
		wantTrigger string
	}{
		{
			name: "label triggers review",
			pr: PullRequest{
				Labels: []Label{{Name: "chetter-review"}},
			},
			repo:   "org/repo",
			files:  nil,
			wantOK: true, wantTrigger: "label",
		},
		{
			name: "fork triggers review",
			pr: PullRequest{
				Head: PRBranch{
					Ref: "feat",
					Repo: struct {
						FullName string `json:"full_name"`
						CloneURL string `json:"clone_url"`
					}{
						FullName: "fork/repo",
						CloneURL: "https://github.com/fork/repo.git",
					},
				},
			},
			repo:   "org/repo",
			files:  nil,
			wantOK: true, wantTrigger: "fork",
		},
		{
			name: "Go file change triggers review",
			pr:   PullRequest{},
			repo: "org/repo",
			files: []string{
				"server/internal/foo.go",
			},
			wantOK: true, wantTrigger: "file-pattern",
		},
		{
			name: "proto file change triggers review",
			pr:   PullRequest{},
			repo: "org/repo",
			files: []string{
				"server/proto/user/v1/user.proto",
			},
			wantOK: true, wantTrigger: "file-pattern",
		},
		{
			name: "migration file triggers review",
			pr:   PullRequest{},
			repo: "org/repo",
			files: []string{
				"server/db/migrations/0001_init.sql",
			},
			wantOK: true, wantTrigger: "file-pattern",
		},
		{
			name: "docs only - no review",
			pr:   PullRequest{},
			repo: "org/repo",
			files: []string{
				"docs/README.md",
				"website/index.html",
			},
			wantOK: false, wantTrigger: "",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			h := &Handler{gh: nil, cfg: HandlerConfig{}}
			ev := PullRequestEvent{
				PullRequest: tc.pr,
			}
			trigger, ok := h.shouldReviewWithFiles(ev, tc.repo, tc.files, tc.filesErr)
			if ok != tc.wantOK {
				t.Errorf("shouldReview returned ok=%v, want %v", ok, tc.wantOK)
			}
			if trigger != tc.wantTrigger {
				t.Errorf("shouldReview returned trigger=%q, want %q", trigger, tc.wantTrigger)
			}
		})
	}
}
